### ISSUE TITLE
Use --require-sandbox (or allow it as an option)

### ISSUE THREAD

**Issue by tsutton** [elm-lang/elm-platform#126]
Since the intention is to install into a sandbox anyway. And, from personal experience, something with my cabal was causing some things to not go into the sandbox until I manually installed things with --require-sandbox.

**Comment by igrep** [comment]
Are you talking about [BuildFromSource.hs](https://github.com/elm-lang/elm-platform/blob/master/installers/BuildFromSource.hs)?

**Comment by jvoigtlaender** [comment]
Which concrete problem would adding `--require-sandbox` fix? In `BuildFromSource.hs`, I don't see how it would fix any actual problem, because there a sandbox is definitely created.

But here is a concrete problem that adding `--require-sandbox` would introduce:
* That option does not exist in `cabal-install` version 1.18.
* So we would have to tell people that they need to use at least version 1.20 of `cabal`.
* That means we would exclude people that are on a system with Haskell Platform 2014.2.0.0. Those people are currently able to build Elm 0.15 using `BuildFromSource.hs`. Afterwards, they wouldn't anymore.

**Comment by jvoigtlaender** [comment]
@tsutton, close this? Otherwise, respond to the above comments?
