### ISSUE TITLE
Upgrading elm from 0.16 to 0.17 using Mac binary

### ISSUE THREAD

**Issue by aldhsu** [elm-lang/elm-platform#154]
## Conditions:
- Install elm 0.16 from Mac binary
- Run [script](https://github.com/elm-lang/elm-platform/blob/master/installers/mac/helper-scripts/uninstall.sh) to delete references
- Install elm 0.17 from Mac binary

## Problem:
Upgrading elm from binary and running package install on a new project returns error: 
- `Error: Unable to find a set of packages that will work with your constraints.`

## Solution:
Stale `package` is left in ~/.elm and builds a faulty elm-package.json and will prevent installing any further dependencies. I just deleted the folder and it should probably be included in the script.

**Comment by jvoigtlaender** [comment]
This is not going to be needed with any version beyond 0.17, because of this: https://github.com/elm-lang/elm-package/commit/645fdb76de86b068857dab4303acbe9f9813178e.

That is, when Elm 0.17.1 or Elm 0.18 comes out, the "stale" `~/.elm/package` will not cause any problems, because the new version will use `~/.elm/0.17.1/package` or `~/.elm/0.18/package` directories.

**Comment by evancz** [comment]
I don't have bandwidth to backport a fix. It's just gonna suck for past versions :/

**Comment by aldhsu** [comment]
That's fine. Thanks for Elm! I put this issue up in case anyone else runs into it.
