### ISSUE TITLE
ELM_HOME not set by BuildFromSource.hs

### ISSUE THREAD

**Issue by pseudonom** [elm-lang/elm-platform#27]
I ran [BuildFromSource.hs](https://github.com/elm-lang/elm-platform/blob/master/src/BuildFromSource.hs).

After successful installation, I ran `elm Foo.elm` and got the following error:

```
elm: user error (Unable to find the ELM_HOME environment variable when searching
for the interfaces.data file.

If you installed Elm Platform with the Mac or Windows installer, it looks like
ELM_HOME was not set automatically. Look up how to set environment variables
on your platform and set ELM_HOME to the directory that contains Elm's static
files:

  * On Mac it is /usr/local/share/elm
  * On Windows it is one of the following:
      C:/Program Files/Elm Platform/0.13/share
      C:/Program Files (x86)/Elm Platform/0.13/share

If it seems like a more complex issue, please report it here:
    <https://github.com/elm-lang/elm-platform/issues>
)
```

Shouldn't BuildFromSource at least output something like:
```
Please add
`export ELM_HOME="foo/Elm-Platform/0.13/Elm/"`
to your shell config.
```
?

**Comment by evancz** [comment]
Sorry to not reply until this issue is quite stale :(

Trying to get resources always goes through [this function](https://github.com/elm-lang/elm-compiler/blob/d5d6028dd9c7389c9987894588cfe26afe72296e/src/Elm/Utils.hs#L97-L112) which will [check if cabal has placed the file in a certain place](https://github.com/elm-lang/elm-compiler/blob/d5d6028dd9c7389c9987894588cfe26afe72296e/src/Elm/Utils.hs#L101). This means that if you build through cabal, you should never need ELM_HOME. If you somehow do need ELM_HOME it may mean that the cabal part got messed up or that your PATH is pointing to something unexpected.

I'll add a note about ELM_HOME in the readme of this repo so people have some clues, but I would not expect the same error to arise with the latest build script under normal circumstances.
