### ISSUE TITLE
Elm not installing on Windows 7. Error Code: 80070002

### ISSUE THREAD

**Issue by soccerfocker** [elm-lang/elm-platform#34]
I just downloaded the Elm installer and tried to install it. 

When I did so, the following error messages came up (in this order):

![elm error message](https://cloud.githubusercontent.com/assets/10411837/5623853/82f87bea-9520-11e4-920d-da9fdf8a0d43.png)
![elm error message 02](https://cloud.githubusercontent.com/assets/10411837/5623855/855ab18c-9520-11e4-9fae-4267fdf16422.png)

It then said Elm had successfully installed. But there's no shortcuts on desktop or any folder or icons in my start menu. There is a folder in my Program Files (x86) that contains a folder called Elm Platform, but the only thing I could get to open on that was elm-reactor and it wouldn't let me type anything.

**Comment by cperkinsintel** [comment]
I did not receive any error messages, but otherwise my experience is similar.  There is a folder in my Program Files (x86) directory, but no shortcuts under my Start menu.

**Comment by evancz** [comment]
@soccerfocker, it sounds like the installer tried to add things to your `PATH` but it was not allowed because you were not admin or something related to permissions. If you run the installer as admin, I'd expect those errors to go away.

@soccerfocker and @cperkinsintel, it sounds like you are expecting some sort of app, but the installer is installing command line tools. So if you go to a `cmd` window and run the `elm-repl` you should be able to type in little Elm expressions and see what they evaluate too. All the command line tools are this way, so clicking on `elm-reactor` isn't the way to go.

Let me know if that clarifies things!

**Comment by jasonzoladz** [comment]
Evan, running as admin doesn't solve the problem.  It's a bug in the installer.  Here's the work-around:

Run "regedit" as administrator and edit the registry key ```HKEY_CURRENT_USER\Environment``` to add ```REG_EXPAND_SZ``` as an entry named ```PATH```.  The value can be set to the empty string ```""```.

**Comment by mcclellanmj** [comment]
This happened to me as well.  It happens if your user has no PATH variable already set.

**Comment by jpierson** [comment]
This happened to me as well on Windows 10. It turns out that creating a user account specific Path environment variable with a value of ";" seems to have worked around the issue. I figured I'd try this afer @mcclellanmj comment.

**Comment by rtfeldman** [comment]
Fixed by https://github.com/elm-lang/elm-platform/pull/87
