### ISSUE TITLE
Why so many installers?

### ISSUE THREAD

**Issue by taoeffect** [elm-lang/elm-platform#99]
Isn't it creating unnecessary work to support Mac and Windows installers, plus a Homebrew recipe?

If Elm can install itself via NPM, perhaps that should be the only way to install it?

**Comment by jvoigtlaender** [comment]
Obviously, not everybody has or wants NPM on their computer, even if they want/need Elm.

For example, say I make students install Elm, because I use it in a course. Many of them will be on Windows, don't have a Node.js installation, and won't need one (as long as I'm not using elm-repl in the course, instead going all visual with elm-reactor from the start).

**Comment by taoeffect** [comment]
Fair enough. Kinda unfortunate.
